build:
  version: "2.0"

account:
  message: "Welcome to EazyBank account related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  liquibase:
    contexts: qa
  logging:
    loki:
      enabled: true
  cache:
    redisson:
      regions:
        entry.expiration.time-to-live: 3600000
        entry.expiration.max_idle_time: 1800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true

logging:
  level:
    ROOT: INFO
    io.github.susimsek.account: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'