build:
  version: "3.0"

account:
  message: "Welcome to EazyBank account related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  liquibase:
    contexts: dev
  logging:
    loki:
      enabled: true
  cache:
    redisson:
      regions:
        testMap:
          expiration:
            time-to-live: 3600000
            max_idle_time: 1800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true

springdoc:
  oAuthFlow:
    tokenUrl: http://localhost:7080/realms/eazybank/protocol/openid-connect/token

logging:
  level:
    ROOT: INFO
    io.github.susimsek.account: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'