server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/accountdb
    username: easybank
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
      pool-name: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.redisson.fallback: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate.cache.redisson.entity.expiration.max_entries: 10000
      hibernate.cache.redisson.entity.expiration.time_to_live: 3600000
      hibernate.cache.redisson.entity.expiration.max_idle_time: 1800000
      hibernate.cache.redisson.query.eviction.max_entries: 10000
      hibernate.cache.redisson.query.eviction.time_to_live: 3600000
      hibernate.cache.redisson.query.eviction.max_idle_time: 1800000
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type
  data:
    redis:
      host: redis
      port: 6379
      password: d41d8cd98f00b204e9800998ecf8427e
  kafka:
    bootstrap-servers: http://kafka:9092
  cloud:
    kubernetes:
      discovery:
        enabled: false
      config:
        enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411

