build:
  version: "3.0"

account:
  message: "Welcome to EazyBank account related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

springdoc:
  oAuthFlow:
    tokenUrl: http://localhost:7080/realms/master/protocol/openid-connect/token