build:
  version: "2.0"

account:
  message: "Welcome to EazyBank account related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0