server:
  shutdown: graceful

build:
  version: "1.0"

account:
  message: "Welcome to EazyBank account related production APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}acfc59b7eb19990a084cf8e17024511670254f67d8b765bd2fda3538f85db0cf81a698183045520fd5e381e1d4efea66"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  liquibase:
    contexts: prod
  logging:
    loki:
      enabled: true
  cache:
    redisson:
      regions:
        testMap:
          expiration:
            time-to-live: 3600000
            max_idle_time: 1800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true

logging:
  level:
    ROOT: INFO
    io.github.susimsek.account: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'