server:
  shutdown: graceful

build:
  version: "1.0"

card:
  message: "Welcome to EazyBank card related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  liquibase:
    contexts: prod


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true