server:
  port: 8070
  shutdown: graceful

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0