server:
  port: 8070
  shutdown: graceful


eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  security:
    user:
      name: easybank
      password: "{cipher}9e37167bf33b458463119a7927279b4f53ea984472903a0c2b61197a8739714b"
      roles: USER, ADMIN
    content-security-policy: "script-src 'self'"
  logging:
    loki:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true