build:
  version: "2.0"

loan:
  message: "Welcome to EazyBank loan related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "cyrano@eazybank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  liquibase:
    contexts: qa
  logging:
    loki:
      enabled: true
  cache:
    redisson:
      regions:
        entry.expiration.max_entries: 10000
        entry.expiration.time-to-live: 3600000
        entry.expiration.max_idle_time: 1800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  observations:
    key-values:
      application: ${spring.application.name}

logging:
  level:
    ROOT: INFO
    io.github.susimsek.loan: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'