build:
  version: "3.0"

loan:
  message: "Welcome to EazyBank loan related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

springdoc:
  oAuthFlow:
    tokenUrl: http://localhost:7080/realms/eazybank/protocol/openid-connect/token