build:
  version: "3.0"

loan:
  message: "Welcome to EazyBank loan related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  liquibase:
    contexts: dev
  logging:
    loki:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true

springdoc:
  oAuthFlow:
    tokenUrl: http://localhost:7080/realms/eazybank/protocol/openid-connect/token

logging:
  level:
    ROOT: INFO
    io.github.susimsek.loan: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'