build:
  version: "1.0"

loan:
  message: "Welcome to EazyBank loan related production APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956


spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0